-- oracle-syslog
-- plugin_id: 1651

DELETE FROM plugin WHERE id = 1651;
DELETE FROM plugin_sid where plugin_id = 1651;

INSERT IGNORE INTO plugin (id, type, name, description, product_type, vendor) VALUES (1651, 1, 'oracle','ORACLE Syslog', 8, 'Oracle');

INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  1, 20, 243, 'oracle: UNKNOWN');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  10000, 20, 238, 'oracle: ALTER');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  10001, 20, 238, 'oracle: CREATE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  10002, 20, 238, 'oracle: DROP');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  1000, 20, 238, 'oracle: FACTOR EVALUATION');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  1001, 20, 238, 'oracle: FACTOR ASSIGNMENT');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  1002, 20, 238, 'oracle: FACTOR EXPRESSION');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  1003, 20, 238, 'oracle: REALM VIOLATION');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  1004, 20, 238, 'oracle: REALM AUTHORIZATION');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  1005, 20, 238, 'oracle: COMMAND AUTHORIZATION');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  1006, 20, 238, 'oracle: SECURE ROLE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  1007, 20, 238, 'oracle: LBL SEC SESSION INIT');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  1008, 20, 236, 'oracle: ACCESS CTRL COMMAND AUTH');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  1009, 20, 236, 'oracle: ACCESS CTRL SESSION INIT');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  100, 20, 236, 'oracle: LOGON');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  1010, 20, 238, 'oracle: LBL SEC ATTEMPT TO UPGRADE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  101, 20, 239, 'oracle: LOGOFF');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  102, 20, 239, 'oracle: LOGOFF BY CLEANUP');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  103, 20, 238, 'oracle: SESSION REC');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  104, 20, 238, 'oracle: SYSTEM AUDIT');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  105, 20, 238, 'oracle: SYSTEM NOAUDIT');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  106, 20, 238, 'oracle: AUDIT DEFAULT');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  107, 20, 238, 'oracle: NOAUDIT DEFAULT');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  108, 20, 238, 'oracle: SYSTEM GRANT');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  109, 20, 238, 'oracle: SYSTEM REVOKE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  10, 20, 238, 'oracle: DROP INDEX');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  110, 20, 238, 'oracle: CREATE PUBLIC SYNONYM');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  111, 20, 238, 'oracle: DROP PUBLIC SYNONYM');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  112, 20, 238, 'oracle: CREATE PUBLIC DATABASE LINK');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  113, 20, 238, 'oracle: DROP PUBLIC DATABASE LINK');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  114, 20, 238, 'oracle: GRANT ROLE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  115, 20, 238, 'oracle: REVOKE ROLE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  116, 20, 238, 'oracle: EXECUTE PROCEDURE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  117, 20, 238, 'oracle: USER COMMENT');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  118, 20, 238, 'oracle: ENABLE TRIGGER');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  119, 20, 238, 'oracle: DISABLE TRIGGER');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  11, 20, 238, 'oracle: ALTER INDEX');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  120, 20, 238, 'oracle: ENABLE ALL TRIGGERS');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  121, 20, 238, 'oracle: DISABLE ALL TRIGGERS');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  122, 20, 238, 'oracle: NETWORK ERROR');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  123, 20, 238, 'oracle: EXECUTE TYPE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  128, 20, 238, 'oracle: FLASHBACK');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  129, 20, 238, 'oracle: CREATE SESSION');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  12, 20, 238, 'oracle: DROP TABLE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  13, 20, 238, 'oracle: CREATE SEQUENCE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  14, 20, 238, 'oracle: ALTER SEQUENCE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  157, 20, 238, 'oracle: CREATE DIRECTORY');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  158, 20, 238, 'oracle: DROP DIRECTORY');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  159, 20, 238, 'oracle: CREATE LIBRARY');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  15, 20, 238, 'oracle: ALTER TABLE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  160, 20, 238, 'oracle: CREATE JAVA');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  161, 20, 238, 'oracle: ALTER JAVA');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  162, 20, 238, 'oracle: DROP JAVA');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  163, 20, 238, 'oracle: CREATE OPERATOR');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  164, 20, 238, 'oracle: CREATE INDEXTYPE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  165, 20, 238, 'oracle: DROP INDEXTYPE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  167, 20, 238, 'oracle: DROP OPERATOR');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  168, 20, 238, 'oracle: ASSOCIATE STATISTICS');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  169, 20, 238, 'oracle: DISASSOCIATE STATISTICS');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  16, 20, 238, 'oracle: DROP SEQUENCE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  170, 20, 238, 'oracle: CALL METHOD');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  171, 20, 238, 'oracle: CREATE SUMMARY');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  172, 20, 238, 'oracle: ALTER SUMMARY');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  173, 20, 238, 'oracle: DROP SUMMARY');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  174, 20, 238, 'oracle: CREATE DIMENSION');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  175, 20, 238, 'oracle: ALTER DIMENSION');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  176, 20, 238, 'oracle: DROP DIMENSION');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  177, 20, 238, 'oracle: CREATE CONTEXT');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  178, 20, 238, 'oracle: DROP CONTEXT');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  179, 20, 238, 'oracle: ALTER OUTLINE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  17, 20, 238, 'oracle: GRANT OBJECT');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  180, 20, 238, 'oracle: CREATE OUTLINE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  181, 20, 238, 'oracle: DROP OUTLINE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  182, 20, 238, 'oracle: UPDATE INDEXES');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  183, 20, 238, 'oracle: ALTER OPERATOR');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  18, 20, 238, 'oracle: REVOKE OBJECT');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  197, 20, 238, 'oracle: PURGE USER_RECYCLEBIN');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  198, 20, 238, 'oracle: PURGE DBA_RECYCLEBIN');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  199, 20, 238, 'oracle: PURGE TABLESPACE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  19, 20, 238, 'oracle: CREATE SYNONYM');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  1, 20, 238, 'oracle: CREATE TABLE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  2000000000, 20, 238, 'oracle: Generic event');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  20000000, 20, 238, 'Demo event (limit reached)');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  200, 20, 238, 'oracle: PURGE TABLE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  201, 20, 238, 'oracle: PURGE INDEX');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  202, 20, 238, 'oracle: UNDROP OBJECT');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  204, 20, 238, 'oracle: FLASHBACK DATABASE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  205, 20, 238, 'oracle: FLASHBACK TABLE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  206, 20, 238, 'oracle: CREATE RESTORE POINT');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  207, 20, 238, 'oracle: DROP RESTORE POINT');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  208, 20, 238, 'oracle: PROXY AUTHENTICATION ONLY');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  209, 20, 238, 'oracle: DECLARE REWRITE EQUIVALENCE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  20, 20, 238, 'oracle: DROP SYNONYM');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  210, 20, 238, 'oracle: ALTER REWRITE EQUIVALENCE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  211, 20, 238, 'oracle: DROP REWRITE EQUIVALENCE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  212, 20, 238, 'oracle: SUPER USER LOGON');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  213, 20, 238, 'oracle: SUPER USER DDL');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  214, 20, 238, 'oracle: SUPER USER DML');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  215, 20, 238, 'oracle: STARTUP');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  216, 20, 239, 'oracle: SHUTDOWN');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  217, 20, 238, 'oracle: SUPER USER UNKNOWN');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  21, 20, 238, 'oracle: CREATE VIEW');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  22, 20, 238, 'oracle: DROP VIEW');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  23, 20, 238, 'oracle: VALIDATE INDEX');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  24, 20, 238, 'oracle: CREATE PROCEDURE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  25, 20, 238, 'oracle: ALTER PROCEDURE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  26, 20, 238, 'oracle: LOCK');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  27, 20, 238, 'oracle: NO-OP');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  28, 20, 238, 'oracle: RENAME');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  29, 20, 238, 'oracle: COMMENT');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  2, 20, 238, 'oracle: INSERT');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  30000, 20, 238, 'oracle: INVALID RECORD');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  30, 20, 238, 'oracle: AUDIT OBJECT');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  31, 20, 238, 'oracle: NOAUDIT OBJECT');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  32, 20, 238, 'oracle: CREATE DATABASE LINK');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  33, 20, 238, 'oracle: DROP DATABASE LINK');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  34, 20, 238, 'oracle: CREATE DATABASE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  35, 20, 238, 'oracle: ALTER DATABASE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  36, 20, 238, 'oracle: CREATE ROLLBACK SEG');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  37, 20, 238, 'oracle: ALTER ROLLBACK SEG');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  38, 20, 238, 'oracle: DROP ROLLBACK SEG');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  39, 20, 238, 'oracle: CREATE TABLESPACE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  3, 20, 238, 'oracle: SELECT');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  40, 20, 238, 'oracle: ALTER TABLESPACE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  41, 20, 238, 'oracle: DROP TABLESPACE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  42, 20, 238, 'oracle: ALTER SESSION');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  43, 20, 238, 'oracle: ALTER USER');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  44, 20, 238, 'oracle: COMMIT');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  45, 20, 238, 'oracle: ROLLBACK');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  46, 20, 238, 'oracle: SAVEPOINT');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  47, 20, 238, 'oracle: PL/SQL EXECUTE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  48, 20, 238, 'oracle: SET TRANSACTION');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  49, 20, 238, 'oracle: ALTER SYSTEM');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  4, 20, 238, 'oracle: CREATE CLUSTER');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  50, 20, 238, 'oracle: EXPLAIN');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  51, 20, 238, 'oracle: CREATE USER');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  52, 20, 238, 'oracle: CREATE ROLE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  53, 20, 238, 'oracle: DROP USER');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  54, 20, 238, 'oracle: DROP ROLE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  55, 20, 238, 'oracle: SET ROLE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  56, 20, 238, 'oracle: CREATE SCHEMA');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  57, 20, 238, 'oracle: CREATE CONTROL FILE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  59, 20, 238, 'oracle: CREATE TRIGGER');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  5, 20, 238, 'oracle: ALTER CLUSTER');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  60, 20, 238, 'oracle: ALTER TRIGGER');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  61, 20, 238, 'oracle: DROP TRIGGER');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  62, 20, 238, 'oracle: ANALYZE TABLE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  63, 20, 238, 'oracle: ANALYZE INDEX');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  64, 20, 238, 'oracle: ANALYZE CLUSTER');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  65, 20, 238, 'oracle: CREATE PROFILE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  66, 20, 238, 'oracle: DROP PROFILE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  67, 20, 238, 'oracle: ALTER PROFILE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  68, 20, 238, 'oracle: DROP PROCEDURE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  6, 20, 238, 'oracle: UPDATE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  70, 20, 238, 'oracle: ALTER RESOURCE COST');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  71, 20, 238, 'oracle: CREATE MATERIALIZED VIEW LOG');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  72, 20, 238, 'oracle: ALTER MATERIALIZED VIEW LOG');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  73, 20, 238, 'oracle: DROP MATERIALIZED VIEW LOG');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  74, 20, 238, 'oracle: CREATE MATERIALIZED VIEW');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  75, 20, 238, 'oracle: ALTER MATERIALIZED VIEW');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  76, 20, 238, 'oracle: DROP MATERIALIZED VIEW');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  77, 20, 238, 'oracle: CREATE TYPE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  78, 20, 238, 'oracle: DROP TYPE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  79, 20, 238, 'oracle: ALTER ROLE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  7, 20, 238, 'oracle: DELETE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  80, 20, 238, 'oracle: ALTER TYPE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  81, 20, 238, 'oracle: CREATE TYPE BODY');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  82, 20, 238, 'oracle: ALTER TYPE BODY');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  83, 20, 238, 'oracle: DROP TYPE BODY');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  84, 20, 238, 'oracle: DROP LIBRARY');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  85, 20, 238, 'oracle: TRUNCATE TABLE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  86, 20, 238, 'oracle: TRUNCATE CLUSTER');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  8, 20, 238, 'oracle: DROP CLUSTER');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  9000, 20, 236, 'oracle: CONNECT');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  91, 20, 238, 'oracle: CREATE FUNCTION');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  92, 20, 238, 'oracle: ALTER FUNCTION');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  93, 20, 238, 'oracle: DROP FUNCTION');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  94, 20, 238, 'oracle: CREATE PACKAGE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  95, 20, 238, 'oracle: ALTER PACKAGE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  96, 20, 238, 'oracle: DROP PACKAGE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  97, 20, 238, 'oracle: CREATE PACKAGE BODY');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  98, 20, 238, 'oracle: ALTER PACKAGE BODY');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  99, 20, 238, 'oracle: DROP PACKAGE BODY');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, subcategory_id, name) VALUES (1651,  9, 20, 238, 'oracle: CREATE INDEX');
